export const AVAILABLE_SUBJECTS = [
  'Mathematics',
  'Physics',
  'Chemistry',
  'English',
  'ICT',
  'Biology',
  'Higher Math',
  'General Science',
  'Bangla',
  'Religious Studies',
  'Accounting',
  'Finance',
  'Economics',
  'Business Studies',
  'Management',
  'Statistics',
  'History',
  'Geography',
  'Social Science',
  'Sociology',
  'Psychology'
];

export const AVAILABLE_CLASSES = [
  'Class 1',
  'Class 2',
  'Class 3',
  'Class 4',
  'Class 5',
  'Class 6',
  'Class 7',
  'Class 8',
  'Class 9',
  'Class 10',
  'SSC Candidate',
  'HSC 1st Year',
  'HSC 2nd Year',
  'HSC Candidate',
  'University Admission'
];
